version: 2

models:
    
    - name: stg_tpch_orders
      description: "Staging model for raw external orders table in S3 (so this is pretty cool)"
      columns:
          - name: order_key
            description: "The primary key for this table"
            tests:
                - unique
                - not_null    